[package]
name = "y2023ex08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
num = "0.4.1"

[[bench]]
name = "bench_y2023ex08"
harness = false

[dev-dependencies]
criterion = "0.5.1"
