[package]
name = "y2021ex19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_y2021ex19"
harness = false

[dependencies]
generator = "0.7.1"
