[package]
name = "y2021ex17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_y2021ex17"
harness = false
